on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pipenv
    - name: build with pyinstaller
      run: |
        pipenv install
        pipenv shell
        pyinstaller -c -F src\main.py
    - name: zip
      uses: papeloto/action-zip@v1
      with:
        files: |
          $GITHUB_WORKSPACE/dist/main.exe
          $GITHUB_WORKSPACE/src/settings.yaml
        recursive: false
        dest: dist/CentralMarketTracker.zip
    - name: "Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Latest Release"
        files: |
          $GITHUB_WORKSPACE/dist/CentralMarketTracker.zip