on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install pipenv
    - name: build with pyinstaller
      run: |
        pipenv install
        pipenv run
        pyinstaller -c -F src\main.py

  zip-files:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: papeloto/action-zip@v1
        with:
          files: |
            dist\main.exe
            src\settings.yaml
          recursive: false
          dest: dist\CentralMarketTracker.zip

  release:
    needs: zip-files
    runs-on: windows-latest
    name: Latest Release
    steps:
      - name: "Build and Release"
        run: |
          echo "done!"
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Release"
          files: |
            dist\CentralMarketTracker.zip
